[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#F59E0B"  # Amber

# Background color for the main content area.
backgroundColor = "#1F2937"  # Gray 900

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#374151"  # Gray 700

# Color used for almost all text.
textColor = "#FFFFFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
