# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent stable version
    hooks:
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # IMPORTANT: Replace 'vX.Y.Z' with the latest stable Ruff version tag from
    # https://github.com/astral-sh/ruff-pre-commit/releases
    # For example, if the latest ruff version is v0.4.4, use that.
    rev: 'v0.4.4' # Please verify and update this to the latest stable version
    hooks:
      - id: ruff-format # Run the formatter first
        # args: [--check] # Uncomment to only check formatting without applying changes
      - id: ruff        # Then run the linter (with auto-fix)
        args: [--fix, --exit-non-zero-on-fix]

# To update hooks to their latest versions in the future, you can run:
# pre-commit autoupdate
