# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent stable version
    hooks:
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

# Temporarily disabled ruff pre-commit hooks due to configuration issues
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   rev: 'v0.4.4'
#   hooks:
#     - id: ruff-format
#     - id: ruff
#       args: [--fix, --ignore=F821,F401,F403,F405,F841,E402]

# To update hooks to their latest versions in the future, you can run:
# pre-commit autoupdate
