# pyproject.toml

[tool.ruff]
# Assume Python 3.9 compatibility. You can change this to your target version.
target-version = "py39"

# Exclude common directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow line lengths up to 88 characters (Black's default).
line-length = 88

[tool.ruff.lint]
# Enable selective linting rules to avoid breaking working code
# E: pycodestyle errors (but exclude line length)
# F: Pyflakes (but exclude some undefined name checks)
# I: isort for import sorting
select = ["E", "F", "I"]

# Ignore specific rules that can break working code
ignore = [
    "E501",  # Line too long (let formatter handle this)
    "F821",  # Undefined name (can break working code with dynamic variables)
]

# Additional safety: don't auto-fix undefined name issues
unfixable = ["F821"]

[tool.ruff.format]
# Enable formatting. This is compatible with Black.
# You can specify options like quote_style if needed, e.g.:
# quote-style = "double"
# indent-style = "space"
