# Top-level settings
line-length = 120
target-version = "py38"
fix = true

# A list of files and directories to exclude from checks.
extend-exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "node_modules",
    "venv",
    ".venv"
]

# Linting section
[lint]
# Enable autofix for all safe fixes.
fixable = ["ALL"]
unfixable = []

# Per-file rule ignores
[lint.per-file-ignores]
"app/ai_data_analyst.py" = ["F401", "E501"]
